services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # 注册命令服务
  ProductRankingBundle\Command\:
    resource: '../../Command/'

  # 注册控制器服务
  ProductRankingBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']

  # 注册事件订阅者
  ProductRankingBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'

  # 注册消息处理器
  ProductRankingBundle\MessageHandler\:
    resource: '../../MessageHandler/'

  # 注册过程服务
  ProductRankingBundle\Procedure\:
    resource: '../../Procedure/'

  # 注册仓储服务
  ProductRankingBundle\Repository\:
    resource: '../../Repository/'

  # 注册业务服务
  ProductRankingBundle\Service\:
    resource: '../../Service/'
